---
# Playbook to undeploy Ghost and its component
# TO DO

# Nota: all = remove tudo, pods, deployments, serviços, etc.
- hosts: localhost
  tasks: 
    - name: Removing Ghost deployment 
      command: kubectl delete all --all -n "{{ namespace }}"

# TODO:
# De momento isto apaga tudo, é preciso separar as coisas!

# Pre definiçao - e feito o undeploy dos serviços ghost, mantendo os dados dos users
#- name: Undeploy Ghost
#  hosts: localhost
#  gather_facts: false
#  roles:
#      - delete_ghost