---

# Undeploy dos serviços do ghost

- hosts: localhost
  tasks: 
    - name: Undeploy Ghost Services
      command: kubectl delete pods,services ghost-blog -n "{{ namespace }}" #; kubectl delete deployment ghost-blog -n "{{ namespace }}"