---
# Playbook to deploy Ghost and its components
# TO DO

- hosts: localhost
  tasks: 
    - name: Creating kubernetes secrets 
      command: kubectl apply -f inventory/secret.yml

- name: Deploy MySQL
  hosts: localhost
  gather_facts: false
  roles:
      - deploy_mysql

- name: Deploy Ghost
  hosts: localhost
  gather_facts: false
  roles:
      - deploy_ghost

