---
apiVersion: v1
kind: Secret
metadata:
	name: ghost-data
  namespace: ghost-namespace
type: Opaque
data:
	password: UGFzc3dvcmQkMTIzNDU2  # Password$123456
	root_password: UGFzc3dvcmQkMTIzNDU2  # Password$123456